#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
test_dir=$(mktemp -d)
trap 'rm -rf "$test_dir"' EXIT HUP INT TERM
compiler=${CC:-cc}
flags='-O2 -Wall -Wextra -Werror'
if [ "${SANITIZE:-0}" = 1 ]; then flags="$flags -fsanitize=address,undefined -fno-omit-frame-pointer -g"; fi
"$compiler" $flags -I"$repo" "$repo/tests/test_tracker.c" "$repo/tracker.c" -o "$test_dir/tracker"
"$test_dir/tracker"
"$compiler" $flags -I"$repo" "$repo/tests/test_image.c" "$repo/image.c" -lm -o "$test_dir/image"
"$test_dir/image" "$test_dir/vft.gray"
"$compiler" $flags -I"$repo" "$repo/tests/test_uvc_bulk.c" "$repo/uvc_bulk.c" -o "$test_dir/uvc-bulk"
"$test_dir/uvc-bulk"
# Generated by the unmodified image pipeline at upstream vft-stream 6678300.
printf 'bf5a2724556d863825cf73cc8747a2fea3b6edd4ca28a9c8e604380b7b864573  %s\n' "$test_dir/vft.gray" | sha256sum -c -
echo 'Original VFT image fixture is byte-for-byte unchanged.'
